reporter: "xcode"

included:
  - cmd/powergrid-app/PowerGrid/PowerGrid
  - cmd/powergrid-app/PowerGrid/PowerGridTests
  - cmd/powergrid-app/PowerGrid/PowerGridUITests

excluded:
  - cmd/powergrid-app/PowerGrid/PowerGrid/internal/rpc
  - cmd/powergrid-app/PowerGrid/PowerGrid.xcodeproj
  - build
  - generated

disabled_rules:
  - trailing_whitespace
  - cyclomatic_complexity
  - function_body_length
  - type_body_length
  - file_length
  - multiple_closures_with_trailing_closure

opt_in_rules:
  - explicit_init
  - empty_count
  - first_where
  - force_unwrapping

line_length:
  warning: 220
  error: 300
  ignores_urls: true
  ignores_comments: true

identifier_name:
  min_length:
    warning: 1
    error: 1
