reporter: "xcode"

included:
  - cmd/powergrid-app/PowerGrid/PowerGrid
  - cmd/powergrid-app/PowerGrid/PowerGridTests
  - cmd/powergrid-app/PowerGrid/PowerGridUITests

excluded:
  - cmd/powergrid-app/PowerGrid/PowerGrid/internal/rpc
  - cmd/powergrid-app/PowerGrid/PowerGrid.xcodeproj
  - build
  - generated

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - explicit_init
  - empty_count
  - first_where
  - force_unwrapping

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true

function_body_length:
  warning: 80
  error: 140

type_body_length:
  warning: 250
  error: 400

file_length:
  warning: 500
  error: 1000
