// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.1
// source: powergrid.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PowerFeature int32

const (
	PowerFeature_POWER_FEATURE_UNSPECIFIED     PowerFeature = 0
	PowerFeature_PREVENT_DISPLAY_SLEEP         PowerFeature = 1
	PowerFeature_PREVENT_SYSTEM_SLEEP          PowerFeature = 2
	PowerFeature_FORCE_DISCHARGE               PowerFeature = 3
	PowerFeature_CONTROL_MAGSAFE_LED           PowerFeature = 4
	PowerFeature_LOW_POWER_MODE                PowerFeature = 5 // Toggle macOS Low Power Mode
	PowerFeature_DISABLE_CHARGING_BEFORE_SLEEP PowerFeature = 6 // Toggle disabling charging before sleep
)

// Enum value maps for PowerFeature.
var (
	PowerFeature_name = map[int32]string{
		0: "POWER_FEATURE_UNSPECIFIED",
		1: "PREVENT_DISPLAY_SLEEP",
		2: "PREVENT_SYSTEM_SLEEP",
		3: "FORCE_DISCHARGE",
		4: "CONTROL_MAGSAFE_LED",
		5: "LOW_POWER_MODE",
		6: "DISABLE_CHARGING_BEFORE_SLEEP",
	}
	PowerFeature_value = map[string]int32{
		"POWER_FEATURE_UNSPECIFIED":     0,
		"PREVENT_DISPLAY_SLEEP":         1,
		"PREVENT_SYSTEM_SLEEP":          2,
		"FORCE_DISCHARGE":               3,
		"CONTROL_MAGSAFE_LED":           4,
		"LOW_POWER_MODE":                5,
		"DISABLE_CHARGING_BEFORE_SLEEP": 6,
	}
)

func (x PowerFeature) Enum() *PowerFeature {
	p := new(PowerFeature)
	*p = x
	return p
}

func (x PowerFeature) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PowerFeature) Descriptor() protoreflect.EnumDescriptor {
	return file_powergrid_proto_enumTypes[0].Descriptor()
}

func (PowerFeature) Type() protoreflect.EnumType {
	return &file_powergrid_proto_enumTypes[0]
}

func (x PowerFeature) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PowerFeature.Descriptor instead.
func (PowerFeature) EnumDescriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{0}
}

type MutationOperation int32

const (
	MutationOperation_MUTATION_OPERATION_UNSPECIFIED MutationOperation = 0
	MutationOperation_SET_CHARGE_LIMIT               MutationOperation = 1
	MutationOperation_SET_POWER_FEATURE              MutationOperation = 2
)

// Enum value maps for MutationOperation.
var (
	MutationOperation_name = map[int32]string{
		0: "MUTATION_OPERATION_UNSPECIFIED",
		1: "SET_CHARGE_LIMIT",
		2: "SET_POWER_FEATURE",
	}
	MutationOperation_value = map[string]int32{
		"MUTATION_OPERATION_UNSPECIFIED": 0,
		"SET_CHARGE_LIMIT":               1,
		"SET_POWER_FEATURE":              2,
	}
)

func (x MutationOperation) Enum() *MutationOperation {
	p := new(MutationOperation)
	*p = x
	return p
}

func (x MutationOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MutationOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_powergrid_proto_enumTypes[1].Descriptor()
}

func (MutationOperation) Type() protoreflect.EnumType {
	return &file_powergrid_proto_enumTypes[1]
}

func (x MutationOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MutationOperation.Descriptor instead.
func (MutationOperation) EnumDescriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_powergrid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_powergrid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	CurrentCharge                    int32                  `protobuf:"varint,1,opt,name=current_charge,json=currentCharge,proto3" json:"current_charge,omitempty"`
	IsCharging                       bool                   `protobuf:"varint,2,opt,name=is_charging,json=isCharging,proto3" json:"is_charging,omitempty"`
	IsConnected                      bool                   `protobuf:"varint,3,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	ChargeLimit                      int32                  `protobuf:"varint,4,opt,name=charge_limit,json=chargeLimit,proto3" json:"charge_limit,omitempty"`
	IsChargeLimited                  bool                   `protobuf:"varint,5,opt,name=is_charge_limited,json=isChargeLimited,proto3" json:"is_charge_limited,omitempty"`
	CycleCount                       int32                  `protobuf:"varint,6,opt,name=cycle_count,json=cycleCount,proto3" json:"cycle_count,omitempty"`
	AdapterDescription               string                 `protobuf:"bytes,7,opt,name=adapter_description,json=adapterDescription,proto3" json:"adapter_description,omitempty"`
	BatteryWattage                   float32                `protobuf:"fixed32,8,opt,name=battery_wattage,json=batteryWattage,proto3" json:"battery_wattage,omitempty"`
	AdapterWattage                   float32                `protobuf:"fixed32,9,opt,name=adapter_wattage,json=adapterWattage,proto3" json:"adapter_wattage,omitempty"`
	SystemWattage                    float32                `protobuf:"fixed32,10,opt,name=system_wattage,json=systemWattage,proto3" json:"system_wattage,omitempty"`
	HealthByMax                      int32                  `protobuf:"varint,11,opt,name=health_by_max,json=healthByMax,proto3" json:"health_by_max,omitempty"`                                                                      // IOKit.Calculations.HealthByMaxCapacity
	AdapterInputVoltage              float32                `protobuf:"fixed32,12,opt,name=adapter_input_voltage,json=adapterInputVoltage,proto3" json:"adapter_input_voltage,omitempty"`                                             // IOKit.Adapter.InputVoltage (V)
	AdapterInputAmperage             float32                `protobuf:"fixed32,13,opt,name=adapter_input_amperage,json=adapterInputAmperage,proto3" json:"adapter_input_amperage,omitempty"`                                          // IOKit.Adapter.InputAmperage (A)
	PreventDisplaySleepActive        bool                   `protobuf:"varint,14,opt,name=prevent_display_sleep_active,json=preventDisplaySleepActive,proto3" json:"prevent_display_sleep_active,omitempty"`                          // Assertion active in this process
	PreventSystemSleepActive         bool                   `protobuf:"varint,15,opt,name=prevent_system_sleep_active,json=preventSystemSleepActive,proto3" json:"prevent_system_sleep_active,omitempty"`                             // Assertion active in this process
	ForceDischargeActive             bool                   `protobuf:"varint,16,opt,name=force_discharge_active,json=forceDischargeActive,proto3" json:"force_discharge_active,omitempty"`                                           // Adapter disabled via SMC
	SmcChargingEnabled               bool                   `protobuf:"varint,17,opt,name=smc_charging_enabled,json=smcChargingEnabled,proto3" json:"smc_charging_enabled,omitempty"`                                                 // SMC.State.IsChargingEnabled
	SmcAdapterEnabled                bool                   `protobuf:"varint,18,opt,name=smc_adapter_enabled,json=smcAdapterEnabled,proto3" json:"smc_adapter_enabled,omitempty"`                                                    // SMC.State.IsAdapterEnabled
	AdapterMaxWatts                  int32                  `protobuf:"varint,19,opt,name=adapter_max_watts,json=adapterMaxWatts,proto3" json:"adapter_max_watts,omitempty"`                                                          // IOKit.Adapter.MaxWatts (W)
	TimeToFullMinutes                int32                  `protobuf:"varint,20,opt,name=time_to_full_minutes,json=timeToFullMinutes,proto3" json:"time_to_full_minutes,omitempty"`                                                  // IOKit.Battery.TimeToFull (minutes)
	TimeToEmptyMinutes               int32                  `protobuf:"varint,21,opt,name=time_to_empty_minutes,json=timeToEmptyMinutes,proto3" json:"time_to_empty_minutes,omitempty"`                                               // IOKit.Battery.TimeToEmpty (minutes)
	MagsafeLedControlActive          bool                   `protobuf:"varint,22,opt,name=magsafe_led_control_active,json=magsafeLedControlActive,proto3" json:"magsafe_led_control_active,omitempty"`                                // Whether daemon is controlling MagSafe LED
	MagsafeLedSupported              bool                   `protobuf:"varint,23,opt,name=magsafe_led_supported,json=magsafeLedSupported,proto3" json:"magsafe_led_supported,omitempty"`                                              // Hardware supports MagSafe LED control
	LowPowerModeEnabled              bool                   `protobuf:"varint,24,opt,name=low_power_mode_enabled,json=lowPowerModeEnabled,proto3" json:"low_power_mode_enabled,omitempty"`                                            // macOS Low Power Mode is enabled
	DisableChargingBeforeSleepActive bool                   `protobuf:"varint,25,opt,name=disable_charging_before_sleep_active,json=disableChargingBeforeSleepActive,proto3" json:"disable_charging_before_sleep_active,omitempty"`   // Whether daemon will disable charging before sleep
	BatterySerialNumber              string                 `protobuf:"bytes,26,opt,name=battery_serial_number,json=batterySerialNumber,proto3" json:"battery_serial_number,omitempty"`                                               // Battery serial number
	BatteryDesignCapacity            int32                  `protobuf:"varint,27,opt,name=battery_design_capacity,json=batteryDesignCapacity,proto3" json:"battery_design_capacity,omitempty"`                                        // mAh
	BatteryMaxCapacity               int32                  `protobuf:"varint,28,opt,name=battery_max_capacity,json=batteryMaxCapacity,proto3" json:"battery_max_capacity,omitempty"`                                                 // mAh (current maximum)
	BatteryNominalCapacity           int32                  `protobuf:"varint,29,opt,name=battery_nominal_capacity,json=batteryNominalCapacity,proto3" json:"battery_nominal_capacity,omitempty"`                                     // mAh (design nominal)
	BatteryVoltage                   float32                `protobuf:"fixed32,30,opt,name=battery_voltage,json=batteryVoltage,proto3" json:"battery_voltage,omitempty"`                                                              // V
	BatteryAmperage                  float32                `protobuf:"fixed32,31,opt,name=battery_amperage,json=batteryAmperage,proto3" json:"battery_amperage,omitempty"`                                                           // A
	BatteryIndividualCellMillivolts  []int32                `protobuf:"varint,32,rep,packed,name=battery_individual_cell_millivolts,json=batteryIndividualCellMillivolts,proto3" json:"battery_individual_cell_millivolts,omitempty"` // Per-cell voltage in mV
	BatteryTemperatureC              float32                `protobuf:"fixed32,33,opt,name=battery_temperature_c,json=batteryTemperatureC,proto3" json:"battery_temperature_c,omitempty"`                                             // °C
	BatteryVoltageDriftMv            int32                  `protobuf:"varint,34,opt,name=battery_voltage_drift_mv,json=batteryVoltageDriftMv,proto3" json:"battery_voltage_drift_mv,omitempty"`                                      // Cell max-min drift in mV
	BatteryBalanceState              string                 `protobuf:"bytes,35,opt,name=battery_balance_state,json=batteryBalanceState,proto3" json:"battery_balance_state,omitempty"`                                               // balanced | slight_imbalance | high_imbalance | unknown
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_powergrid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powergrid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetCurrentCharge() int32 {
	if x != nil {
		return x.CurrentCharge
	}
	return 0
}

func (x *StatusResponse) GetIsCharging() bool {
	if x != nil {
		return x.IsCharging
	}
	return false
}

func (x *StatusResponse) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *StatusResponse) GetChargeLimit() int32 {
	if x != nil {
		return x.ChargeLimit
	}
	return 0
}

func (x *StatusResponse) GetIsChargeLimited() bool {
	if x != nil {
		return x.IsChargeLimited
	}
	return false
}

func (x *StatusResponse) GetCycleCount() int32 {
	if x != nil {
		return x.CycleCount
	}
	return 0
}

func (x *StatusResponse) GetAdapterDescription() string {
	if x != nil {
		return x.AdapterDescription
	}
	return ""
}

func (x *StatusResponse) GetBatteryWattage() float32 {
	if x != nil {
		return x.BatteryWattage
	}
	return 0
}

func (x *StatusResponse) GetAdapterWattage() float32 {
	if x != nil {
		return x.AdapterWattage
	}
	return 0
}

func (x *StatusResponse) GetSystemWattage() float32 {
	if x != nil {
		return x.SystemWattage
	}
	return 0
}

func (x *StatusResponse) GetHealthByMax() int32 {
	if x != nil {
		return x.HealthByMax
	}
	return 0
}

func (x *StatusResponse) GetAdapterInputVoltage() float32 {
	if x != nil {
		return x.AdapterInputVoltage
	}
	return 0
}

func (x *StatusResponse) GetAdapterInputAmperage() float32 {
	if x != nil {
		return x.AdapterInputAmperage
	}
	return 0
}

func (x *StatusResponse) GetPreventDisplaySleepActive() bool {
	if x != nil {
		return x.PreventDisplaySleepActive
	}
	return false
}

func (x *StatusResponse) GetPreventSystemSleepActive() bool {
	if x != nil {
		return x.PreventSystemSleepActive
	}
	return false
}

func (x *StatusResponse) GetForceDischargeActive() bool {
	if x != nil {
		return x.ForceDischargeActive
	}
	return false
}

func (x *StatusResponse) GetSmcChargingEnabled() bool {
	if x != nil {
		return x.SmcChargingEnabled
	}
	return false
}

func (x *StatusResponse) GetSmcAdapterEnabled() bool {
	if x != nil {
		return x.SmcAdapterEnabled
	}
	return false
}

func (x *StatusResponse) GetAdapterMaxWatts() int32 {
	if x != nil {
		return x.AdapterMaxWatts
	}
	return 0
}

func (x *StatusResponse) GetTimeToFullMinutes() int32 {
	if x != nil {
		return x.TimeToFullMinutes
	}
	return 0
}

func (x *StatusResponse) GetTimeToEmptyMinutes() int32 {
	if x != nil {
		return x.TimeToEmptyMinutes
	}
	return 0
}

func (x *StatusResponse) GetMagsafeLedControlActive() bool {
	if x != nil {
		return x.MagsafeLedControlActive
	}
	return false
}

func (x *StatusResponse) GetMagsafeLedSupported() bool {
	if x != nil {
		return x.MagsafeLedSupported
	}
	return false
}

func (x *StatusResponse) GetLowPowerModeEnabled() bool {
	if x != nil {
		return x.LowPowerModeEnabled
	}
	return false
}

func (x *StatusResponse) GetDisableChargingBeforeSleepActive() bool {
	if x != nil {
		return x.DisableChargingBeforeSleepActive
	}
	return false
}

func (x *StatusResponse) GetBatterySerialNumber() string {
	if x != nil {
		return x.BatterySerialNumber
	}
	return ""
}

func (x *StatusResponse) GetBatteryDesignCapacity() int32 {
	if x != nil {
		return x.BatteryDesignCapacity
	}
	return 0
}

func (x *StatusResponse) GetBatteryMaxCapacity() int32 {
	if x != nil {
		return x.BatteryMaxCapacity
	}
	return 0
}

func (x *StatusResponse) GetBatteryNominalCapacity() int32 {
	if x != nil {
		return x.BatteryNominalCapacity
	}
	return 0
}

func (x *StatusResponse) GetBatteryVoltage() float32 {
	if x != nil {
		return x.BatteryVoltage
	}
	return 0
}

func (x *StatusResponse) GetBatteryAmperage() float32 {
	if x != nil {
		return x.BatteryAmperage
	}
	return 0
}

func (x *StatusResponse) GetBatteryIndividualCellMillivolts() []int32 {
	if x != nil {
		return x.BatteryIndividualCellMillivolts
	}
	return nil
}

func (x *StatusResponse) GetBatteryTemperatureC() float32 {
	if x != nil {
		return x.BatteryTemperatureC
	}
	return 0
}

func (x *StatusResponse) GetBatteryVoltageDriftMv() int32 {
	if x != nil {
		return x.BatteryVoltageDriftMv
	}
	return 0
}

func (x *StatusResponse) GetBatteryBalanceState() string {
	if x != nil {
		return x.BatteryBalanceState
	}
	return ""
}

type MutationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     MutationOperation      `protobuf:"varint,1,opt,name=operation,proto3,enum=rpc.MutationOperation" json:"operation,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Feature       PowerFeature           `protobuf:"varint,3,opt,name=feature,proto3,enum=rpc.PowerFeature" json:"feature,omitempty"`
	Enable        bool                   `protobuf:"varint,4,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutationRequest) Reset() {
	*x = MutationRequest{}
	mi := &file_powergrid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationRequest) ProtoMessage() {}

func (x *MutationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_powergrid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationRequest.ProtoReflect.Descriptor instead.
func (*MutationRequest) Descriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{2}
}

func (x *MutationRequest) GetOperation() MutationOperation {
	if x != nil {
		return x.Operation
	}
	return MutationOperation_MUTATION_OPERATION_UNSPECIFIED
}

func (x *MutationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *MutationRequest) GetFeature() PowerFeature {
	if x != nil {
		return x.Feature
	}
	return PowerFeature_POWER_FEATURE_UNSPECIFIED
}

func (x *MutationRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type VersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildId       string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"` // Daemon build identifier (e.g., SHA-256 of executable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionResponse) Reset() {
	*x = VersionResponse{}
	mi := &file_powergrid_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionResponse) ProtoMessage() {}

func (x *VersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powergrid_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionResponse.ProtoReflect.Descriptor instead.
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{3}
}

func (x *VersionResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

type DaemonInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	BuildId             string                 `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	AuthMode            string                 `protobuf:"bytes,2,opt,name=auth_mode,json=authMode,proto3" json:"auth_mode,omitempty"`
	MagsafeLedSupported bool                   `protobuf:"varint,3,opt,name=magsafe_led_supported,json=magsafeLedSupported,proto3" json:"magsafe_led_supported,omitempty"`
	BuildIdSource       string                 `protobuf:"bytes,4,opt,name=build_id_source,json=buildIdSource,proto3" json:"build_id_source,omitempty"` // git, override, fallback, unknown
	BuildDirty          bool                   `protobuf:"varint,5,opt,name=build_dirty,json=buildDirty,proto3" json:"build_dirty,omitempty"`
	ApiMajor            uint32                 `protobuf:"varint,6,opt,name=api_major,json=apiMajor,proto3" json:"api_major,omitempty"`
	ApiMinor            uint32                 `protobuf:"varint,7,opt,name=api_minor,json=apiMinor,proto3" json:"api_minor,omitempty"`
	Capabilities        []string               `protobuf:"bytes,8,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DaemonInfoResponse) Reset() {
	*x = DaemonInfoResponse{}
	mi := &file_powergrid_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonInfoResponse) ProtoMessage() {}

func (x *DaemonInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_powergrid_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonInfoResponse.ProtoReflect.Descriptor instead.
func (*DaemonInfoResponse) Descriptor() ([]byte, []int) {
	return file_powergrid_proto_rawDescGZIP(), []int{4}
}

func (x *DaemonInfoResponse) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *DaemonInfoResponse) GetAuthMode() string {
	if x != nil {
		return x.AuthMode
	}
	return ""
}

func (x *DaemonInfoResponse) GetMagsafeLedSupported() bool {
	if x != nil {
		return x.MagsafeLedSupported
	}
	return false
}

func (x *DaemonInfoResponse) GetBuildIdSource() string {
	if x != nil {
		return x.BuildIdSource
	}
	return ""
}

func (x *DaemonInfoResponse) GetBuildDirty() bool {
	if x != nil {
		return x.BuildDirty
	}
	return false
}

func (x *DaemonInfoResponse) GetApiMajor() uint32 {
	if x != nil {
		return x.ApiMajor
	}
	return 0
}

func (x *DaemonInfoResponse) GetApiMinor() uint32 {
	if x != nil {
		return x.ApiMinor
	}
	return 0
}

func (x *DaemonInfoResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_powergrid_proto protoreflect.FileDescriptor

const file_powergrid_proto_rawDesc = "" +
	"\n" +
	"\x0fpowergrid.proto\x12\x03rpc\"\a\n" +
	"\x05Empty\"\xdb\r\n" +
	"\x0eStatusResponse\x12%\n" +
	"\x0ecurrent_charge\x18\x01 \x01(\x05R\rcurrentCharge\x12\x1f\n" +
	"\vis_charging\x18\x02 \x01(\bR\n" +
	"isCharging\x12!\n" +
	"\fis_connected\x18\x03 \x01(\bR\visConnected\x12!\n" +
	"\fcharge_limit\x18\x04 \x01(\x05R\vchargeLimit\x12*\n" +
	"\x11is_charge_limited\x18\x05 \x01(\bR\x0fisChargeLimited\x12\x1f\n" +
	"\vcycle_count\x18\x06 \x01(\x05R\n" +
	"cycleCount\x12/\n" +
	"\x13adapter_description\x18\a \x01(\tR\x12adapterDescription\x12'\n" +
	"\x0fbattery_wattage\x18\b \x01(\x02R\x0ebatteryWattage\x12'\n" +
	"\x0fadapter_wattage\x18\t \x01(\x02R\x0eadapterWattage\x12%\n" +
	"\x0esystem_wattage\x18\n" +
	" \x01(\x02R\rsystemWattage\x12\"\n" +
	"\rhealth_by_max\x18\v \x01(\x05R\vhealthByMax\x122\n" +
	"\x15adapter_input_voltage\x18\f \x01(\x02R\x13adapterInputVoltage\x124\n" +
	"\x16adapter_input_amperage\x18\r \x01(\x02R\x14adapterInputAmperage\x12?\n" +
	"\x1cprevent_display_sleep_active\x18\x0e \x01(\bR\x19preventDisplaySleepActive\x12=\n" +
	"\x1bprevent_system_sleep_active\x18\x0f \x01(\bR\x18preventSystemSleepActive\x124\n" +
	"\x16force_discharge_active\x18\x10 \x01(\bR\x14forceDischargeActive\x120\n" +
	"\x14smc_charging_enabled\x18\x11 \x01(\bR\x12smcChargingEnabled\x12.\n" +
	"\x13smc_adapter_enabled\x18\x12 \x01(\bR\x11smcAdapterEnabled\x12*\n" +
	"\x11adapter_max_watts\x18\x13 \x01(\x05R\x0fadapterMaxWatts\x12/\n" +
	"\x14time_to_full_minutes\x18\x14 \x01(\x05R\x11timeToFullMinutes\x121\n" +
	"\x15time_to_empty_minutes\x18\x15 \x01(\x05R\x12timeToEmptyMinutes\x12;\n" +
	"\x1amagsafe_led_control_active\x18\x16 \x01(\bR\x17magsafeLedControlActive\x122\n" +
	"\x15magsafe_led_supported\x18\x17 \x01(\bR\x13magsafeLedSupported\x123\n" +
	"\x16low_power_mode_enabled\x18\x18 \x01(\bR\x13lowPowerModeEnabled\x12N\n" +
	"$disable_charging_before_sleep_active\x18\x19 \x01(\bR disableChargingBeforeSleepActive\x122\n" +
	"\x15battery_serial_number\x18\x1a \x01(\tR\x13batterySerialNumber\x126\n" +
	"\x17battery_design_capacity\x18\x1b \x01(\x05R\x15batteryDesignCapacity\x120\n" +
	"\x14battery_max_capacity\x18\x1c \x01(\x05R\x12batteryMaxCapacity\x128\n" +
	"\x18battery_nominal_capacity\x18\x1d \x01(\x05R\x16batteryNominalCapacity\x12'\n" +
	"\x0fbattery_voltage\x18\x1e \x01(\x02R\x0ebatteryVoltage\x12)\n" +
	"\x10battery_amperage\x18\x1f \x01(\x02R\x0fbatteryAmperage\x12K\n" +
	"\"battery_individual_cell_millivolts\x18  \x03(\x05R\x1fbatteryIndividualCellMillivolts\x122\n" +
	"\x15battery_temperature_c\x18! \x01(\x02R\x13batteryTemperatureC\x127\n" +
	"\x18battery_voltage_drift_mv\x18\" \x01(\x05R\x15batteryVoltageDriftMv\x122\n" +
	"\x15battery_balance_state\x18# \x01(\tR\x13batteryBalanceState\"\xa2\x01\n" +
	"\x0fMutationRequest\x124\n" +
	"\toperation\x18\x01 \x01(\x0e2\x16.rpc.MutationOperationR\toperation\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12+\n" +
	"\afeature\x18\x03 \x01(\x0e2\x11.rpc.PowerFeatureR\afeature\x12\x16\n" +
	"\x06enable\x18\x04 \x01(\bR\x06enable\",\n" +
	"\x0fVersionResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\"\xa7\x02\n" +
	"\x12DaemonInfoResponse\x12\x19\n" +
	"\bbuild_id\x18\x01 \x01(\tR\abuildId\x12\x1b\n" +
	"\tauth_mode\x18\x02 \x01(\tR\bauthMode\x122\n" +
	"\x15magsafe_led_supported\x18\x03 \x01(\bR\x13magsafeLedSupported\x12&\n" +
	"\x0fbuild_id_source\x18\x04 \x01(\tR\rbuildIdSource\x12\x1f\n" +
	"\vbuild_dirty\x18\x05 \x01(\bR\n" +
	"buildDirty\x12\x1b\n" +
	"\tapi_major\x18\x06 \x01(\rR\bapiMajor\x12\x1b\n" +
	"\tapi_minor\x18\a \x01(\rR\bapiMinor\x12\"\n" +
	"\fcapabilities\x18\b \x03(\tR\fcapabilities*\xc7\x01\n" +
	"\fPowerFeature\x12\x1d\n" +
	"\x19POWER_FEATURE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PREVENT_DISPLAY_SLEEP\x10\x01\x12\x18\n" +
	"\x14PREVENT_SYSTEM_SLEEP\x10\x02\x12\x13\n" +
	"\x0fFORCE_DISCHARGE\x10\x03\x12\x17\n" +
	"\x13CONTROL_MAGSAFE_LED\x10\x04\x12\x12\n" +
	"\x0eLOW_POWER_MODE\x10\x05\x12!\n" +
	"\x1dDISABLE_CHARGING_BEFORE_SLEEP\x10\x06*d\n" +
	"\x11MutationOperation\x12\"\n" +
	"\x1eMUTATION_OPERATION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SET_CHARGE_LIMIT\x10\x01\x12\x15\n" +
	"\x11SET_POWER_FEATURE\x10\x022\xd2\x01\n" +
	"\tPowerGrid\x12,\n" +
	"\tGetStatus\x12\n" +
	".rpc.Empty\x1a\x13.rpc.StatusResponse\x121\n" +
	"\rApplyMutation\x12\x14.rpc.MutationRequest\x1a\n" +
	".rpc.Empty\x12.\n" +
	"\n" +
	"GetVersion\x12\n" +
	".rpc.Empty\x1a\x14.rpc.VersionResponse\x124\n" +
	"\rGetDaemonInfo\x12\n" +
	".rpc.Empty\x1a\x17.rpc.DaemonInfoResponseB\x18Z\x16powergrid/internal/rpcb\x06proto3"

var (
	file_powergrid_proto_rawDescOnce sync.Once
	file_powergrid_proto_rawDescData []byte
)

func file_powergrid_proto_rawDescGZIP() []byte {
	file_powergrid_proto_rawDescOnce.Do(func() {
		file_powergrid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_powergrid_proto_rawDesc), len(file_powergrid_proto_rawDesc)))
	})
	return file_powergrid_proto_rawDescData
}

var file_powergrid_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_powergrid_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_powergrid_proto_goTypes = []any{
	(PowerFeature)(0),          // 0: rpc.PowerFeature
	(MutationOperation)(0),     // 1: rpc.MutationOperation
	(*Empty)(nil),              // 2: rpc.Empty
	(*StatusResponse)(nil),     // 3: rpc.StatusResponse
	(*MutationRequest)(nil),    // 4: rpc.MutationRequest
	(*VersionResponse)(nil),    // 5: rpc.VersionResponse
	(*DaemonInfoResponse)(nil), // 6: rpc.DaemonInfoResponse
}
var file_powergrid_proto_depIdxs = []int32{
	1, // 0: rpc.MutationRequest.operation:type_name -> rpc.MutationOperation
	0, // 1: rpc.MutationRequest.feature:type_name -> rpc.PowerFeature
	2, // 2: rpc.PowerGrid.GetStatus:input_type -> rpc.Empty
	4, // 3: rpc.PowerGrid.ApplyMutation:input_type -> rpc.MutationRequest
	2, // 4: rpc.PowerGrid.GetVersion:input_type -> rpc.Empty
	2, // 5: rpc.PowerGrid.GetDaemonInfo:input_type -> rpc.Empty
	3, // 6: rpc.PowerGrid.GetStatus:output_type -> rpc.StatusResponse
	2, // 7: rpc.PowerGrid.ApplyMutation:output_type -> rpc.Empty
	5, // 8: rpc.PowerGrid.GetVersion:output_type -> rpc.VersionResponse
	6, // 9: rpc.PowerGrid.GetDaemonInfo:output_type -> rpc.DaemonInfoResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_powergrid_proto_init() }
func file_powergrid_proto_init() {
	if File_powergrid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_powergrid_proto_rawDesc), len(file_powergrid_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_powergrid_proto_goTypes,
		DependencyIndexes: file_powergrid_proto_depIdxs,
		EnumInfos:         file_powergrid_proto_enumTypes,
		MessageInfos:      file_powergrid_proto_msgTypes,
	}.Build()
	File_powergrid_proto = out.File
	file_powergrid_proto_goTypes = nil
	file_powergrid_proto_depIdxs = nil
}
