// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: powergrid.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PowerGrid_GetStatus_FullMethodName     = "/rpc.PowerGrid/GetStatus"
	PowerGrid_ApplyMutation_FullMethodName = "/rpc.PowerGrid/ApplyMutation"
	PowerGrid_GetVersion_FullMethodName    = "/rpc.PowerGrid/GetVersion"
	PowerGrid_GetDaemonInfo_FullMethodName = "/rpc.PowerGrid/GetDaemonInfo"
)

// PowerGridClient is the client API for PowerGrid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PowerGridClient interface {
	GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error)
	ApplyMutation(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*Empty, error)
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
	GetDaemonInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DaemonInfoResponse, error)
}

type powerGridClient struct {
	cc grpc.ClientConnInterface
}

func NewPowerGridClient(cc grpc.ClientConnInterface) PowerGridClient {
	return &powerGridClient{cc}
}

func (c *powerGridClient) GetStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, PowerGrid_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridClient) ApplyMutation(ctx context.Context, in *MutationRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, PowerGrid_ApplyMutation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, PowerGrid_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *powerGridClient) GetDaemonInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DaemonInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonInfoResponse)
	err := c.cc.Invoke(ctx, PowerGrid_GetDaemonInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowerGridServer is the server API for PowerGrid service.
// All implementations must embed UnimplementedPowerGridServer
// for forward compatibility.
type PowerGridServer interface {
	GetStatus(context.Context, *Empty) (*StatusResponse, error)
	ApplyMutation(context.Context, *MutationRequest) (*Empty, error)
	GetVersion(context.Context, *Empty) (*VersionResponse, error)
	GetDaemonInfo(context.Context, *Empty) (*DaemonInfoResponse, error)
	mustEmbedUnimplementedPowerGridServer()
}

// UnimplementedPowerGridServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPowerGridServer struct{}

func (UnimplementedPowerGridServer) GetStatus(context.Context, *Empty) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPowerGridServer) ApplyMutation(context.Context, *MutationRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyMutation not implemented")
}
func (UnimplementedPowerGridServer) GetVersion(context.Context, *Empty) (*VersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedPowerGridServer) GetDaemonInfo(context.Context, *Empty) (*DaemonInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDaemonInfo not implemented")
}
func (UnimplementedPowerGridServer) mustEmbedUnimplementedPowerGridServer() {}
func (UnimplementedPowerGridServer) testEmbeddedByValue()                   {}

// UnsafePowerGridServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowerGridServer will
// result in compilation errors.
type UnsafePowerGridServer interface {
	mustEmbedUnimplementedPowerGridServer()
}

func RegisterPowerGridServer(s grpc.ServiceRegistrar, srv PowerGridServer) {
	// If the following call pancis, it indicates UnimplementedPowerGridServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PowerGrid_ServiceDesc, srv)
}

func _PowerGrid_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGrid_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServer).GetStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGrid_ApplyMutation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServer).ApplyMutation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGrid_ApplyMutation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServer).ApplyMutation(ctx, req.(*MutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGrid_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGrid_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PowerGrid_GetDaemonInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerGridServer).GetDaemonInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PowerGrid_GetDaemonInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerGridServer).GetDaemonInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PowerGrid_ServiceDesc is the grpc.ServiceDesc for PowerGrid service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PowerGrid_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.PowerGrid",
	HandlerType: (*PowerGridServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStatus",
			Handler:    _PowerGrid_GetStatus_Handler,
		},
		{
			MethodName: "ApplyMutation",
			Handler:    _PowerGrid_ApplyMutation_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _PowerGrid_GetVersion_Handler,
		},
		{
			MethodName: "GetDaemonInfo",
			Handler:    _PowerGrid_GetDaemonInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "powergrid.proto",
}
